[project]
name = "AudioBookRequest"
version = "1.10.5"
requires-python = ">= 3.14"
readme = "README.md"
dependencies = [
    "aiohttp>=3.14.2",
    "alembic>=1.18.5",
    "apscheduler>=3.11.3",
    "argon2-cffi>=25.1.0",
    "argon2-cffi-bindings>=25.1.0",
    "cryptography>=49.0.0",
    "fastapi[standard]>=0.139.2",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.6",
    "jinja2-fragments>=1.12.0",
    "jinja2-htmlmin>=1.1.0",
    "jinjax>=0.65",
    "markdown>=3.10.2",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-core>=2.46.4",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "python-multipart>=0.0.32",
    "rapidfuzz>=3.14.5",
    "requests>=2.34.2",
    "sqlmodel>=0.0.39",
    "structlog>=26.1.0",
    "terminaltables>=3.1.10",
    "torf>=4.3.1",
    "torrent-parser>=0.4.1",
    "typer>=0.27.0",
    "urllib3>=2.7.0",
]

# setuptools by default expects a "src" folder structure
[tool.setuptools.packages.find]
where = ["."]

[tool.uv]
package = false

[tool.djlint]
profile = "django"
ignore = "H021"
format_js=true
line_break_after_multiline_tag=true
max_blank_lines=1
# NOTE: custom_html formats documents, but also adds quotes around attributes breaking jinjax
# custom_html="BaseLayout,Index.PopularSection,BookCard"
ignore_case=true




[tool.basedpyright]
typeCheckingMode = "all"
include = ["app"]
reportDeprecated = false
reportUnusedCallResult = false
allowedUntypedLibraries = ["apscheduler", "torrent_parser", "jinjax"]

[dependency-groups]
dev = [
    "basedpyright>=1.39.9",
    "djlint>=1.42.1",
    "ruff>=0.15.22",
]
