"""add missing psql migrations

Revision ID: 03bea7e891dd
Revises: 592ca7993f69
Create Date: 2025-09-29 18:22:08.855291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03bea7e891dd"
down_revision: Union[str, None] = "592ca7993f69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookrequest", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_asin_user", ["asin", "user_username"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        group_type = sa.Enum("untrusted", "trusted", "admin", name="groupenum")
        group_type.create(op.get_bind(), checkfirst=True)
        if op.get_bind().dialect.name == "postgresql":
            batch_op.execute(
                'ALTER TABLE "user" ALTER COLUMN "group" TYPE groupenum USING "group"::groupenum'
            )
        else:
            batch_op.alter_column(
                "group",
                existing_type=sa.VARCHAR(),
                type_=group_type,
                existing_nullable=False,
                existing_server_default=sa.text("'untrusted'::character varying"),
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "group",
            existing_type=sa.Enum("untrusted", "trusted", "admin", name="groupenum"),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            existing_server_default=sa.text("'untrusted'::character varying"),
        )

    with op.batch_alter_table("bookrequest", schema=None) as batch_op:
        batch_op.drop_constraint("unique_asin_user", type_="unique")

    # ### end Alembic commands ###
