"""add mam_id to bookrequest

Revision ID: 0c948752a9c2
Revises: d0fac85afd0f
Create Date: 2026-01-21 12:05:52.910804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c948752a9c2'
down_revision: Union[str, None] = 'd0fac85afd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobookrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mam_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audiobookrequest_mam_id'), ['mam_id'], unique=False)

    with op.batch_alter_table('manualbookrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mam_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_manualbookrequest_mam_id'), ['mam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manualbookrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manualbookrequest_mam_id'))
        batch_op.drop_column('mam_id')

    with op.batch_alter_table('audiobookrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiobookrequest_mam_id'))
        batch_op.drop_column('mam_id')

    # ### end Alembic commands ###
