"""add_audiobook_extra_metadata

Revision ID: 2a148b82b875
Revises: f3b47c8d9e2a
Create Date: 2026-01-23 23:43:11.204966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a148b82b875'
down_revision: Union[str, None] = 'f3b47c8d9e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('libraryimportitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraryimportitem_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libraryimportitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraryimportitem_session_id'))

    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('description')
        batch_op.drop_column('publisher')
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
