"""add request log table

Revision ID: a1b2c3d4e5f6
Revises: 03bea7e891dd
Create Date: 2026-01-26 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "03bea7e891dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requestlog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("info", "warning", "error", name="requestloglevel"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requestlog_asin"), "requestlog", ["asin"], unique=False)
    op.create_index(
        op.f("ix_requestlog_user_username"),
        "requestlog",
        ["user_username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requestlog_user_username"), table_name="requestlog")
    op.drop_index(op.f("ix_requestlog_asin"), table_name="requestlog")
    op.drop_table("requestlog")
    op.execute("DROP TYPE IF EXISTS requestloglevel")
    # ### end Alembic commands ###
