"""Add download tracking fields to AudiobookRequest

Revision ID: e58129ba2119
Revises: 1adb2da9bf9b
Create Date: 2026-01-22 09:15:49.829072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e58129ba2119'
down_revision: Union[str, None] = '1adb2da9bf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobookrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torrent_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('download_progress', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('download_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_index(batch_op.f('ix_audiobookrequest_torrent_hash'), ['torrent_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobookrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiobookrequest_torrent_hash'))
        batch_op.drop_column('processing_status')
        batch_op.drop_column('download_state')
        batch_op.drop_column('download_progress')
        batch_op.drop_column('torrent_hash')

    # ### end Alembic commands ###
