name: Check Format

on:
  push:
    paths:
      - "**.py"
      - "**.html"
      - "**.css"
      - "**.yaml"
  pull_request:
    paths:
      - "**.py"
      - "**.html"
      - "**.css"
      - "**.yaml"

jobs:
  test:
    name: Test types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.22"

      - run: uv sync --all-extras --dev

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Check Template Formats
        run: uv run djlint templates/

      - name: Check Template Formats
        run: uv run ruff format --check app/
