name: Check Format

on:
  push:
    paths:
      - "**.py"
      - "**.html"
      - "**.css"
      - "**.yaml"

jobs:
  test:
    name: Test types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v4

      - run: uv sync --all-extras

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Check Template Formats
        run: just test_format
